name: Publish to Maven Central

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '1.0.0'

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Set up Maven settings
      uses: s4u/maven-settings-action@v3.0.0
      with:
        servers: |
          [{
            "id": "ossrh",
            "username": "${{ secrets.OSSRH_USERNAME }}",
            "password": "${{ secrets.OSSRH_PASSWORD }}"
          }]
        profiles: |
          [{
            "id": "release",
            "properties": {
              "gpg.executable": "gpg",
              "gpg.keyname": "${{ secrets.GPG_KEY_ID }}",
              "gpg.passphrase": "${{ secrets.GPG_PASSPHRASE }}"
            }
          }]
          
    - name: Import GPG key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
        
    - name: Run tests
      run: mvn clean test
      
    - name: Deploy to Maven Central
      run: mvn clean deploy -P release --no-transfer-progress --batch-mode
      env:
        MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: maven-artifacts
        path: target/*.jar
